# Development image
FROM python:3.12.4

WORKDIR /usr/src/app

COPY . .

RUN pip install watchdog
RUN pip install --no-cache-dir -r requirements.txt

# CMD ["watchmedo", "auto-restart", "--recursive", "--patterns=*.py", "--", "python", "neurons/miner.py"]
